_target_: topobenchmarkx.model.TBXModel

model_name: sann
model_domain: simplicial

feature_encoder:
  _target_: topobenchmarkx.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: SANNFeatureEncoder
  dataset_in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  in_channels: ${transforms.sann_encoding.in_channels} 
  # - - ${get_list_element:${model.feature_encoder.dataset_in_channels},0}
  #   - 6
  #   - 18
  # - - ${get_list_element:${model.feature_encoder.dataset_in_channels},1}
  #   - 12
  #   - 39
  # - - ${get_list_element:${model.feature_encoder.dataset_in_channels},2}
  #   - 9
  #   - 30
#${infer_in_channels:${dataset},${oc.select:transforms,null}}
  out_channels: 64
  proj_dropout: 0.0
  selected_dimensions:
    - 0
    - 1
    - 2
  feature_lifting: Duplicate
  all_ones: true

backbone:
  _target_: topobenchmarkx.nn.backbones.simplicial.sann.SANN
  in_channels: ${model.backbone.hidden_channels}
  n_layers: 2
  hidden_channels: ${model.feature_encoder.out_channels}

backbone_wrapper:
  _target_: topobenchmarkx.nn.wrappers.SANNWrapper
  _partial_: true
  wrapper_name: SANNWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infere_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobenchmarkx.nn.readouts.${model.readout.readout_name}
  readout_name: SANNReadout  #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  num_cell_dimensions: ${infere_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum

# compile model for faster training with pytorch 2.0
compile: false
