_target_: topobenchmark.model.TBModel

model_name: sccnn 
model_domain: simplicial

feature_encoder:
  _target_: topobenchmark.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  out_channels: 32
  proj_dropout: 0.0
  selected_dimensions:
    - 0
    - 1
    - 2

backbone:
  _target_: topomodelx.nn.simplicial.sccnn.SCCNN
  in_channels_all:
    - ${model.feature_encoder.out_channels}
    - ${model.feature_encoder.out_channels}
    - ${model.feature_encoder.out_channels}
  hidden_channels_all:
    - ${model.backbone.in_channels_all[0]}
    - ${model.backbone.in_channels_all[1]}
    - ${model.backbone.in_channels_all[2]}
  conv_order: 1 # Increasing order make the training unstable
  sc_order: 3
  aggr_norm: False
  update_func: "sigmoid"
  n_layers: 1

backbone_wrapper:
  _target_: topobenchmark.nn.wrappers.SCCNNWrapper
  _partial_: true
  wrapper_name: SCCNNWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infere_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobenchmark.nn.readouts.${model.readout.readout_name}
  readout_name: PropagateSignalDown #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  num_cell_dimensions: ${infere_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum

# compile model for faster training with pytorch 2.0
compile: false
