_target_: topobenchmarkx.transforms.data_transform.DataTransform
transform_name: "AddGPSEInformation"
transform_type: "data manipulation"
max_rank: 3
copy_initial: True
neighborhoods:  
  - 'up_incidence-1'
dim_out: 11
max_hop: 2
dim_target_node: 51
dim_target_graph: 11
pretrain_model: ZINC
in_channels:
- - 3
  - 3
  - 3
- - 3
  - 3
  - 3
- - 3
  - 51
  - 51
#complex_dim: ${oc.select:dataset.parameters.max_dim_if_lifted,3}
#in_channels: ${infer_in_khop_feature_dim:${model.feature_encoder.dataset_in_channels},${.max_hop}} 
# in_features: ${infer_in_sann_khop_feature_dim:${model},${3}} 


# change of the transfroms: ${new function that looks at dataset.dim (list [3,5,1])} --> list of dim