_target_: topobenchmarkx.transforms.data_transform.DataTransform
transform_name: "AddGPSEInformation"
transform_type: "data manipulation"
max_rank: 2
copy_initial: True
neighborhoods:  
  - 'incidence_1'
dim_out: 11
max_hop: ${get_hop_num_gpse:${.copy_initial}}
dim_target_node: 51
dim_target_graph: 11
pretrain_model: PCQM4MV2
in_channels: ${infer_in_hasse_graph_agg_dim:${.neighborhoods}, ${.max_rank},${oc.select:dataset.parameters.num_features},${.dim_target_graph}, ${.dim_target_node}, ${.copy_initial}}
device: ${trainer.accelerator}
cuda: ${trainer.devices}
#complex_dim: ${oc.select:dataset.parameters.max_dim_if_lifted,3}
#in_channels: ${infer_in_khop_feature_dim:${model.feature_encoder.dataset_in_channels},${.max_hop}} 
# in_features: ${infer_in_sann_khop_feature_dim:${model},${3}} 


# change of the transfroms: ${new function that looks at dataset.dim (list [3,5,1])} --> list of dim