_target_: topobenchmarkx.transforms.data_transform.DataTransform
transform_name: "DifferentGausFeatures"
transform_type: "data manipulation"

mean: 0
std: 0.1
num_features: ${dataset.parameters.num_features}
dimensions: 0

