_target_: topobenchmark.transforms.data_transform.DataTransform
transform_name: "MessagePassingHomophily"
transform_type: "data manipulation"
num_steps: 10
incidence_field: "incidence_hyperedges" # incidence_hyperedges for hypergraphs, incidence_1,..,incidence_k for other domains