_target_: topobenchmark.transforms.data_transform.DataTransform
transform_name: "RemoveExtraFeatureFromProteins"
transform_type: "data manipulation"
remove_first_n_features: 1
search_field: "x_"
expected_number_of_features: ${dataset.parameters.num_features}

