_target_: topobenchmark.evaluator.evaluator.TBEvaluator
task: ${dataset.parameters.task}
task_level: ${dataset.parameters.task_level}
num_classes: ${dataset.parameters.num_classes}

# Metrics
metrics:  [accuracy, precision, recall, auroc] #Available options: accuracy, auroc, precision, recall