_target_: topobenchmark.evaluator.evaluator.TBEvaluator
task: ${dataset.parameters.task}
task_level: ${dataset.parameters.task_level}
num_classes: ${dataset.parameters.num_classes}

# Metrics
metrics: [mae, mse] #Available options: mae, mse