# Dataset loader config
loader:
  _target_: topobenchmark.data.loaders.CitationHypergraphDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: cocitation
    data_name: cocitation_pubmed
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 500
  num_classes: 3
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node

#splits
split_params:
  learning_setting: transductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 1 # Fixed
  num_workers: 1
  pin_memory: False
