_target_: topobenchmarkx.io.load.loaders.GraphLoader

defaults:
  - transforms: ${get_default_transform:graph,${model}}
  

# Data definition
parameters:
  data_domain: graph
  data_type: cornel
  year: 2012
  data_name: US-county-demos
  data_dir: ${paths.data_dir}${dataset.parameters.data_domain}/${dataset.parameters.data_type}
  data_split_dir: ${paths.data_dir}data_splits/${dataset.parameters.data_name}

  # Dataset parameters
  num_features: 6
  num_classes: 1
  task: regression
  task_variable: 'Election' # options: ['Election', 'MedianIncome', 'MigraRate', 'BirthRate', 'DeathRate', 'BachelorRate', 'UnemploymentRate']
  loss_type: mse
  monitor_metric: mse
  task_level: node
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

  # Dataloader parameters
  batch_size: 1 # Fixed
  num_workers: 1
  pin_memory: False
