_target_: topobenchmarkx.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "HypergraphKHopLifting"
k_value: 1
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}