_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "HypergraphKHopLifting"
k_value: 1
feature_lifting: ProjectionSum
neighborhoods: ${oc.select:model.backbone.neighborhoods,null}