# Dataset loader config
loader:
  _target_: topobenchmark.data.loaders.MoleculeDatasetLoader
  parameters: 
    data_domain: graph
    data_type: AQSOL
    data_name: AQSOL
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 21
  max_node_degree: 20
  num_classes: 1
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: 'fixed' # ZINC accept only <fixed> split

# Dataloader parameters
dataloader_params:
  batch_size: 10 # We have an issue with allowing multiple graphs in a batch due to sparse incidences
  num_workers: 0
  pin_memory: False

