# Dataset loader config
loader:
 _target_: topobenchmarkx.data.loaders.H36MDatasetLoader
 parameters: 
   data_domain: graph
   data_type: motion
   data_name: H36MDataset
   data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
 num_features: 1 # one feature per node
 num_classes: 1 # number of output features per node
 task: regression
 loss_type: mse
 monitor_metric: mae
 task_level: node

# Splits configuration
split_params:
 learning_setting: inductive
 data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
 data_seed: 0
 split_type: random
 train_prop: 0.5

# Dataloader parameters
dataloader_params:
 batch_size: 1       # Fixed
 num_workers: 0
 pin_memory: False