# Dataset loader config
loader:
  _target_: topobenchmark.data.loaders.ManualGraphDatasetLoader
  parameters: 
    data_domain: graph
    data_type: manual_dataset
    data_name: manual
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 1
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node

#splits
split_params:
  learning_setting: transductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 2 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting
  standardize: True

# Dataloader parameters
dataloader_params:
  batch_size: 1 
  num_workers: 1
  pin_memory: False
