loader:
  _target_: topobenchmark.data.loaders.TUDatasetLoader
  parameters: 
    data_domain: graph
    data_type: TUDataset
    data_name: NCI109
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 38
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 64
  num_workers: 0
  pin_memory: False



