# USE python train.py dataset.transforms.one_hot_node_degree_features.degrees_fields=x to run this dataset

# Dataset loader config
loader:
  _target_: topobenchmark.data.loaders.MoleculeDatasetLoader
  parameters: 
    data_domain: graph
    data_type: ZINC
    data_name: ZINC
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 21 # torch_geometric ZINC dataset has 21 atom types
  max_node_degree: 20 # Use it to one_hot encode node degrees. Additional parameter to run dataset.transforms.one_hot_node_degree_features.degrees_fields=x
  num_classes: 1
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: graph
  degrees_fields: "x" # Additional parameter to run dataset.transforms.one_hot_node_degree_features.degrees_fields=x

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: 'fixed' # ZINC accept only <fixed> split

# Dataloader parameters
dataloader_params:
  batch_size: 128
  num_workers: 0
  pin_memory: False
  persistent_workers: False
