_target_: topobenchmarkx.network_module.NetworkModule

model_name: cwn_dcm
model_domain: cell

feature_encoder:
  _target_: topobenchmarkx.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}} 
  out_channels: 32
  proj_dropout: 0.
  selected_dimensions:
    - 0
    - 1

backbone:
  _target_: custom_models.cell.cccn.CCCN
  in_channels: ${model.feature_encoder.out_channels}
  n_layers: 4
  dropout: 0.0

backbone_wrapper:
  _target_: topobenchmarkx.nn.wrappers.CCCNWrapper
  _partial_: true
  wrapper_name: CCCNWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infere_list_length:${model.feature_encoder.selected_dimensions}}

readout:
  _target_: topobenchmarkx.nn.readouts.${model.readout.readout_name}
  readout_name: PropagateSignalDown #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  num_cell_dimensions: ${infere_list_length:${model.feature_encoder.selected_dimensions}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum

# compile model for faster training with pytorch 2.0
compile: false
