_target_: topobenchmark.model.TBModel

model_name: topotune
model_domain: cell
tune_gnn: IdentityGCN

feature_encoder:
  _target_: topobenchmark.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}} 
  out_channels: 32
  proj_dropout: 0.
  selected_dimensions:
    - 0
    - 1
    - 2

backbone:
  _target_: topobenchmark.nn.backbones.combinatorial.gccn.TopoTune
  GNN:
    _target_: topobenchmark.nn.backbones.graph.${model.tune_gnn}
    in_channels: ${model.feature_encoder.out_channels}
    out_channels: ${model.feature_encoder.out_channels}
    hidden_channels: ${model.feature_encoder.out_channels}
    num_layers: 2
    dropout: 0.0
    norm: BatchNorm
  neighborhoods:
    - up_adjacency-1
    - up_incidence-0
    - down_incidence-2
    - 2-up_adjacency-0
  layers: 2
  use_edge_attr: false
  activation: relu

backbone_wrapper:
  _target_: topobenchmark.nn.wrappers.combinatorial.TuneWrapper
  _partial_: true
  wrapper_name: TuneWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infere_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobenchmark.nn.readouts.${model.readout.readout_name}
  readout_name: PropagateSignalDown #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  num_cell_dimensions: ${infere_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum

# compile model for faster training with pytorch 2.0
compile: false
